DROP TABLE IF EXISTS `testDB`.`users`;

CREATE TABLE `testDB`.`users`(
  `ramen_id` INT(5) NOT NULL UNIQUE AUTO_INCREMENT
  `store` VARCHAR(50) NOT NULL,
  `menu` VARCHAR(30) NOT NULL,
  `address` VARCHAR(100) DEFAULT "記載ナシ",
  `station` VARCHAR(20) DEFAULT "記載ナシ",
  `taste_id` INT(2) NOT NULL,
  `price` INT(5) NOT NULL DEFAULT 99999,
  `evaluation` FLOAT(3) NOT NULL DEFAULT 99.9,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ramen_id`)
)


